baseurl = "http://johng.de/" # baseurl = "https://jhgee.github.io/johng/"
languageCode = "de-de"
title = "John's Travel Blog"
theme = "robust"

[Params]
Author = "John Henri"
GoogleAnalyticsUserID = "UA-82434346-1"
